 ---

- name: create elastic ip
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_region: "us-east-1"
    aws_access_key: "access key"
    aws_secret_key: "secret key"

  # create an AWS Elastic IP.
  # This is the IP address we will attach to the NAT Gatway.
  # we will own that IP address.
  # That means if later we want to use a different service for NAT,
  # we will be able to use that IP. 

  - name: Setup AWS CLI (1/3)
    shell: >
      aws configure set aws_access_key_id "{{ aws_access_key }}"

  - name: Setup AWS CLI (2/3)
    shell: >
      aws configure set aws_secret_access_key "{{ aws_secret_key }}"

  - name: Setup AWS CLI (3/3)
    shell: >
      aws configure set region {{ aws_region }}

  - name: Create Elastic IP
    shell: >
        aws ec2 allocate-address --domain vpc --query AllocationId | tr -d '"'
    register: eip

  - debug: var=eip

  - name: Set EIP in variable
    set_fact:
      my_elastic_ip: "{{ eip.stdout }}"