---

- name: create subnets public and private
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    project: testing
    vpc_id: "id"
    vpc_cidr_block: "10.0.0.0/16"
    aws_region: "us-east-1"
    aws_access_key: "access key"
    aws_secret_key: "secret key"
    private_subnet_1_cidr: "10.0.0.0/24"
    public_subnet_1_cidr: "10.0.0.0/24"

  # create the subnets.
  # One public, one private.
  # Both subnets are located in the same AZ.
  # we save their ids in variables.

  - name:               Create Public Subnet
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      cidr:             "{{ public_subnet_1_cidr }}"
      az:               "{{ aws_region }}a"
      region:           "{{ aws_region }}"
      aws_access_key:   "{{ aws_access_key }}"
      aws_secret_key:   "{{ aws_secret_key }}"
      resource_tags:
        Name:           "{{ project }} Public Subnet"
    register: my_public_subnet

  - name:               Set Public Subnet ID in variable
    set_fact:
      public_subnet_id: "{{ my_public_subnet.subnet.id }}"

  - name:               Create Private Subnet
    ec2_vpc_subnet:
      state:            "present"
      vpc_id:           "{{ vpc_id }}"
      cidr:             "{{ private_subnet_1_cidr }}"
      az:               "{{ aws_region }}a"
      region:           "{{ aws_region }}"
      aws_access_key:   "{{ aws_access_key }}"
      aws_secret_key:   "{{ aws_secret_key }}"
      resource_tags:
        Name:           "{{ project }} Private Subnet"
    register: my_private_subnet

  - name:               Set Private Subnet ID in variable
    set_fact:
      private_subnet_id: "{{ my_private_subnet.subnet.id }}"
